# Generated by Django 4.1.5 on 2023-02-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpy_lecture', '0003_alter_mytext_board_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytext',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
